### ISSUE TITLE
Bug: Doesn't work when used with the latest GH release

### ISSUE THREAD

**Issue by codefriar** [hectcastro/gh-metrics#88]
Currently using the following versions:
```sh
gh extension list
NAME        REPO                   VERSION
gh metrics  hectcastro/gh-metrics  v3.0.0


gh version
gh version 2.43.1 (2024-01-31)
https://github.com/cli/cli/releases/tag/v2.43.1
```

whenever I run `gh metrics` regardless of the arguments given, it always reports back that 

```sh
gh metrics
2024/02/13 00:09:24 To authenticate, please run `gh auth login`.
``` 

I have verified that I am logged in. 

Please advise

**Comment by hectcastro** [comment]
Interesting. @codefriar, can you please try v3.0.1? I was able to reproduce your issue locally on v3.0.0 and now the extension is working as expected on v3.0.1.

```console
$ gh extension upgrade metrics
```

**Comment by codefriar** [comment]
@hectcastro That did it! Thank you!  Love your work.
